### ISSUE TITLE
"Negative repeat count does nothing"

### ISSUE THREAD

**Issue by s0r00t** [darac/irssi-powerline#1]
Arch x64, Guake+tmux, the theme is broken.
I get spammed with this message : 
![The bug.](http://i.imgur.com/ujO2X35.png)

**Comment by darac** [comment]
This appears to be a bug with adv_windowlist interacting with perl 5.21 ("Negative repeat count does nothing" is a [new warning in 5.21](http://perldoc.perl.org/perl5211delta.html#New-Diagnostics)). I've updated the included version of adv_windowlist.pl to the latest on [Nei's site](http://anti.teamidiot.de/static/nei/*/Code/Irssi/), which does claim to support perl 5.22.

**Comment by s0r00t** [comment]
Alright, it's fixed. However, the powerline characters are not using the background of the terminal; instead they use the color of the statusbar : 
![Wrong color](http://i.imgur.com/0qY0m4y.png)

**Comment by darac** [comment]
Fixed in 0c2d875483ec86854f1288e53f38906bc16d1576.
