### ISSUE TITLE
I can't seem to get this to look like the screenshot at all

### ISSUE THREAD

**Issue by slackhead** [darac/irssi-powerline#4]
I installed the config, theme and awl and it looks nothing like it's supposed to.

A screenshot: http://www.r0t.uk/sshots/shot-1897253180.png

Why is the current channel red and why no > >? Am I missing something?

**Comment by her** [comment]
Did you make a backup of your .irssi? Try reloading the backup and working through the steps again, post each step you did here. Also what OS and CLI App are you using?

**Comment by slackhead** [comment]
I backed up my old config and used the one supplied.

OS is slackware 14.1, terminal is terminator set for green on black.

**Comment by slackhead** [comment]
I've just started with a clean .irssi and same problem. Maybe it's the terminal font (dejavu sans mono) but it's strange if it is.

*Edit: Tried urxvt, xfce terminal, xterm. Just cannot get those >'s

File list:
./config
./default.theme
./solarized-powerline.theme
./scripts
./scripts/autorun
./scripts/autorun/adv_windowlist.pl

**Comment by slackhead** [comment]
Ok I've found out that I needed the powerline version of DejaVu font. Now I have >'s.

Just need to tweak the colours a bit.

**Comment by slackhead** [comment]
Closing...
