### ISSUE TITLE
 'AWL: Run adv_windowlist from the shell or switch to sbar mode'

### ISSUE THREAD

**Issue by gvoysey** [darac/irssi-powerline#8]
error on installation.   There are two status lines at the bottom of an irssi session: the uppermost renders correctly with powerline; the bottom merely displays this text on a grey background. 

`set awl_viewer off` adds the window lists, but it does not display them with powerline formatting. 

The chat text entry line is also ugly / unformatted.

irssi: 1.01 (installed from source)
os: debian wheezy

**Comment by gvoysey** [comment]
in particular, it looks like this: 
![image](https://cloud.githubusercontent.com/assets/3641839/22767219/fed1b484-ee47-11e6-85df-1e247f0c7b31.png)

**Comment by darac** [comment]
Hmm. The provided config should already be setting `awl_viewer = "no"` (line 422),  so you shouldn't need to do that again.

Secondly, it _looks_ like your terminal isn't interpreting ANSI escape codes correctly (the `[7mB` bit). Can I ask what terminal (emulator) you're using and what you have $TERM set to?

Thanks.

**Comment by gvoysey** [comment]
As i was stepping through answering your question, i tried simplifying my setup.  It was originally iterm2 --> ssh --> wheezy --> tmux -->irssi. 

I removed tmux and this renders perfectly well -- so this isn't your fault, it's tmuxs'.   Thanks for the rubber-duck session! 😊
